config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :inventories
  resources :categories
  resources :products
  resources :blogs
  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord class
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
# frozen_string_literal: true

# Blog class
class Blog < ApplicationRecord
end

app/models/camera.rb
# frozen_string_literal: true

class Camera < Product
end

app/models/camera_category.rb
# frozen_string_literal: true

class CameraCategory < Category
end

app/models/category.rb
# frozen_string_literal: true

# Category class
class Category < ApplicationRecord
  has_many :inventories, dependent: :destroy
  has_many :products, through: :inventories

  validates :name, presence: true, uniqueness: true

  before_save :capitalize_name

  enum type: { 'PhoneCategory' => 0, 'CameraCategory' => 1, 'ComputerCategory' => 2 }

  private

  def capitalize_name
    self.name = name.capitalize
  end
end

app/models/computer.rb
# frozen_string_literal: true

class Computer < Product
end

app/models/computer_category.rb
# frozen_string_literal: true

class ComputerCategory < Category
end

app/models/coupon.rb
# frozen_string_literal: true

# Coupon class
class Coupon < ApplicationRecord
  has_many :menus, as: :menu, dependent: :destroy
end

app/models/customer.rb
# frozen_string_literal: true

# Customer class
class Customer < ApplicationRecord
  has_many :payments, dependent: :destroy

  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :phone_number, format: { with: /^\+\d+$/, multiline: true }

  enum gender: { male: 0, female: 1 }
  enum plan: { free: 0, medium: 1, plus: 2 }

  def full_name
    "#{first_name} #{last_name}"
  end

  # scope :not_free, -> { where('plan != 0') } # this scope is provided by enum

  # query in rails console to find customers in Hue: Customer.where(address: 'Hue')
  scope :in_hue, -> { where('address = ?', 'Hue') }
  # rails console, check for first customer is free or not: Customer.find(1).free?
  scope :reg_in22, -> { where(registration_date: '2022-1-1'.to_date..'2022-12-31'.to_date) }
end

app/models/inventory.rb
# frozen_string_literal: true

# Inventory class
class Inventory < ApplicationRecord
  belongs_to :product
  belongs_to :category

  scope :products_in_cat, ->(cat_id) { where('category_id = ?', cat_id) }
end

app/models/payment.rb
# frozen_string_literal: true

# Payment class
class Payment < ApplicationRecord
  belongs_to :customer
  has_many :payment_details, dependent: :destroy
  accepts_nested_attributes_for :payment_details

  before_save :set_total

  def set_total
    self.total = payment_details.map(&:menu).sum(&:price)
  end

  # Example Payment:
  # payment = { name: 'payment_name2', customer_id: 1,
  # payment_details_attributes: [{ menu_type: 'Timeprice', menu_id: 1 },
  # { menu_type: 'Coupon', menu_id: 1 }] }
end

app/models/payment_detail.rb
# frozen_string_literal: true

# PaymentDetail class
class PaymentDetail < ApplicationRecord
  belongs_to :payment
  belongs_to :menu, polymorphic: true
end

app/models/phone.rb
# frozen_string_literal: true

class Phone < Product
end

app/models/phone_category.rb
# frozen_string_literal: true

class PhoneCategory < Category
end

app/models/product.rb
# frozen_string_literal: true

# Product class
class Product < ApplicationRecord
  has_many :inventories, dependent: :destroy
  has_many :categories, through: :inventories

  validates :name, presence: true
  validates :price, presence: true

  def out_of_stock?
    inventories.sum(&:stock) <= 5
  end

  enum type: { 'Phone' => 0, 'Camera' => 1, 'Computer' => 2 }
  serialize :properties
end

app/models/timeprice.rb
# frozen_string_literal: true

# Timeprice class
class Timeprice < ApplicationRecord
  has_many :menus, as: :menu, dependent: :destroy
end

app/helpers/blogs_helper.rb
# frozen_string_literal: true

# Helper module for blogs
module BlogsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# Helper module for categories
module CategoriesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

# Helper module for pages
module PagesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# Helper module for products
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script>
      window.onload = () => {
        const mobileMenuIcon = document.getElementById('mobile-menu-button');
        mobileMenuIcon.addEventListener('click', () => {
          if(mobileMenuIcon.classList.contains('open')){
            mobileMenuIcon.classList.remove('open');
          }else{
            mobileMenuIcon.classList.add('open');
          }
        })
      }
    </script>
  </head>

  <body>
    <main>
      <header class='text-zinc-200'>
        <nav class='sticky flex top-0 bg-gradient-to-r from-rose-500 to-pink-500'>
          <div class='flex items-center p-2 gap-2'>
            <%= image_tag 'logo', width: '50x', height: '50x' %>
            <div class='font-bold text-2xl'>
              Company <span class='text-sky-900' > Name </span>
            </div>
          </div>
          <div class='md:hidden block ml-auto pr-4 my-auto cursor-pointer'>
            <div id='mobile-menu-button' class='group'>
              <div class='bg-zinc-200 rounded-full w-8 h-1 m-1 group-open:rotate-45 transition-all group-open:top-2 relative top-0'></div>
              <div class='opacity-100 group-open:opacity-0 bg-zinc-200 rounded-full w-8 h-1 m-1 transition-all'></div>
              <div class='bg-zinc-200 rounded-full w-8 h-1 m-1 group-open:-rotate-45 transition-all group-open:-top-2 relative top-0'></div>
            </div>
            <div class='absolute top-[62px] bg-gradient-to-r from-rose-500 to-pink-500 w-full left-0'>mobile menu</div>
          </div>
          <div class='hidden flex-1 md:flex items-center justify-end'>
            <div class='menu-item'><span>Home</span></div>
            <div class='menu-item'><a href=<%= blogs_path %>><span>Blogs</span></a></div>
            <div class='menu-item group'><span>Products</span>
              <div class='group-hover:block hidden bg-pink-500 absolute top-full right-0 whitespace-nowrap rounded-b-md text-right'>
                <div class='p-4 font-bold hover:bg-white/5 hover:text-zinc-200 transition-colors ease-in-out cursor-pointer text-pink-200'>
                  <span>First</span>
                </div>
                <div class='p-4 font-bold hover:bg-white/5 hover:text-zinc-200 transition-colors ease-in-out cursor-pointer text-pink-200'>
                  <span>Second</span>
                </div>
              </div>
            </div>
            <div class='menu-item'><span>Categories</span></div>
          </div>
        </nav>
      </header>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>This is the homepage</h1>